var SCRIPT_TITLE="VOCALOID Inter-Note Accent";
function getClientInfo(){return{name:SV.T(SCRIPT_TITLE),category:"eli_lab - VOCALOID Tuning Lab",author:"eli_lab",versionNumber:3,minEditorVersion:67840};}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
var PARTICLES=["は","が","を","に","へ","と","で","も","の","ね","よ","さ","ぞ","な","や"];
function particle(s){return PARTICLES.indexOf(s||"")>=0;}
function nb(n,o){var g=n.getParent(),i=n.getIndexInParent()+o;return i<0||i>=g.getNumNotes()?null:g.getNote(i);}
function score(n){var p=nb(n,-1),x=nb(n,1),q=SV.QUARTER,d=n.getDuration(),ni=x?x.getPitch()-n.getPitch():0,pi=p?n.getPitch()-p.getPitch():0;var s=.25+clamp(d/(q*2),0,1)*.25+clamp(Math.max(Math.abs(pi),Math.abs(ni))/7,0,1)*.35;if(!p||n.getOnset()-p.getEnd()>q*.2)s+=.08;if(!x||x.getOnset()-n.getEnd()>q*.2)s+=.10;if(p&&p.getPitch()===n.getPitch())s-=.08;if(particle(n.getLyrics()))s-=.25;return{score:clamp(s,.05,1.4),ni:ni,pi:pi,particle:particle(n.getLyrics())};}
function add(auto,t,v){auto.add(Math.round(t),clamp(v,-1200,1200));}
function main(){var notes=SV.getMainEditor().getSelection().getSelectedNotes();if(notes.length<2){SV.showMessageBox(SV.T(SCRIPT_TITLE),SV.T("Select at least two notes."));return;}notes.sort(function(a,b){return a.getOnset()-b.getOnset();});var r=SV.showCustomDialog({title:SV.T(SCRIPT_TITLE),message:"Create deliberate pitch events at boundaries between neighboring notes. Context is calculated directly; no analyzer cache is required.",buttons:"OkCancel",widgets:[{name:"style",type:"ComboBox",label:"Transition",choices:["Scoop Into Next","Dip Between","Overshoot Next","Double Accent","Broken"],default:0},{name:"strength",type:"ComboBox",label:"Strength",choices:["Light","Classic","Hard","Extreme"],default:1},{name:"timing",type:"ComboBox",label:"Timing",choices:["Tight","Normal","Wide"],default:1},{name:"largeJumps",type:"ComboBox",label:"Large intervals",choices:["Normal","Reduce","Emphasize"],default:2},{name:"particles",type:"ComboBox",label:"Particle transitions",choices:["Avoid","Subtle","Allow"],default:0}]});if(!r.status)return;var style=parseInt(r.answers.style),strength=[8,15,25,40][parseInt(r.answers.strength)],win=[.035,.065,.11][parseInt(r.answers.timing)],jumpMode=parseInt(r.answers.largeJumps),pm=parseInt(r.answers.particles);for(var i=0;i<notes.length-1;i++){var l=notes[i],n=notes[i+1];if(l.getParent()!==n.getParent()||l.getEnd()>n.getOnset())continue;var a=score(n);if(a.particle&&pm===0)continue;var jump=Math.abs(n.getPitch()-l.getPitch()),amount=strength*(.55+a.score*.85);if(jumpMode===1&&jump>=5)amount*=.65;if(jumpMode===2&&jump>=5)amount*=1.35;if(a.particle)amount*=pm===1?.35:.65;var b=n.getOnset(),pre=Math.min(win*SV.QUARTER,n.getDuration()*.18,l.getDuration()*.18),post=Math.min(win*SV.QUARTER,n.getDuration()*.22),dir=n.getPitch()>l.getPitch()?1:n.getPitch()<l.getPitch()?-1:1,auto=n.getParent().getParameter("pitchDelta");if(style===0){add(auto,b-pre,-dir*amount*.35);add(auto,b-pre*.35,dir*amount*.35);add(auto,b+post*.45,dir*amount*.75);add(auto,b+post,0);}else if(style===1){add(auto,b-pre,dir*amount*.45);add(auto,b,-dir*amount);add(auto,b+post*.55,dir*amount*.18);add(auto,b+post,0);}else if(style===2){add(auto,b-pre,dir*amount*.25);add(auto,b+post*.25,dir*amount);add(auto,b+post*.70,-dir*amount*.18);add(auto,b+post,0);}else if(style===3){add(auto,b-pre,-dir*amount*.55);add(auto,b-pre*.30,dir*amount);add(auto,b+post*.25,-dir*amount*.45);add(auto,b+post*.55,dir*amount*.65);add(auto,b+post,0);}else{add(auto,b-pre,dir*amount);add(auto,b-pre*.45,-dir*amount*.55);add(auto,b+post*.15,dir*amount*.35);add(auto,b+post*.50,-dir*amount*.22);add(auto,b+post,0);}}SV.finish();}
