var PROFILE={title:"VOCALOID Classic Tuning Emulator",category:"eli_lab - VOCALOID Tuning Lab",attack:20,accent:10,vib:7,rate:2.4,onset:.38,irr:.16,fall:13};
function getClientInfo(){return{name:SV.T(PROFILE.title),category:PROFILE.category,author:"eli_lab",versionNumber:4,minEditorVersion:65537}}
function C(v,a,b){return Math.max(a,Math.min(b,v))}function R(a,b){return a+Math.random()*(b-a)}function Q(a){return a[Math.floor(Math.random()*a.length)]}function P(a,t,v){a.add(Math.round(t),C(v,-1200,1200))}
function particle(s){return ["は","が","を","に","へ","と","で","も","の","ね","よ","さ","ぞ","な","や"].indexOf(s)>=0}function weak(s){return ["っ","ー","ん","る","れ","ろ","す","つ","く","き"].indexOf(s)>=0}
function I(ns,i){var n=ns[i],p=i?ns[i-1]:null,x=i+1<ns.length?ns[i+1]:null,l=n.getLyrics?n.getLyrics():"";return{n:n,d:n.getDuration(),prev:p?n.getPitch()-p.getPitch():0,next:x?x.getPitch()-n.getPitch():0,samePrev:!!p&&p.getPitch()===n.getPitch(),sameNext:!!x&&x.getPitch()===n.getPitch(),first:i===0,last:i===ns.length-1,particle:particle(l),weak:weak(l)}}
function W(x){var q=SV.QUARTER,w=.38+C(x.d/(q*2),0,1)*.28+C(Math.max(Math.abs(x.prev),Math.abs(x.next))/7,0,1)*.24;if(x.first||x.last)w+=.08;if(x.samePrev)w-=.08;if(x.particle)w-=.22;if(x.weak)w-=.1;return C(w,.08,1.25)}
function A(a,x,m){var d=x.d;if(!d)return;var dir=x.prev>0?1:x.prev<0?-1:Q([-1,1]),amt=PROFILE.attack*m*(.42+Math.min(1,Math.abs(x.prev)/7)*.62)*(.65+W(x)*.5);if(x.samePrev)amt*=.62;if(x.particle)amt*=.55;var s=x.n.getOnset();P(a,s,0);P(a,s+d*R(.025,.075),dir*amt*R(.55,1));P(a,s+d*R(.09,.18),dir*amt*R(.25,.75));P(a,s+d*R(.18,.28),R(-2,2))}
function X(a,x,m){var d=x.d,amt=PROFILE.accent*m*(.28+C(1-d/(SV.QUARTER*2),0,1)*.48+W(x)*.55);if(x.particle)amt*=.22;if(x.weak)amt*=.45;if(x.first||x.last)amt*=1.12;if(Math.abs(x.next)>=5)amt*=1.12;var dir=x.next>0?1:x.next<0?-1:Q([-1,1]),s=x.n.getOnset();P(a,s+d*R(.2,.38),dir*amt*R(.45,1));P(a,s+d*R(.42,.62),dir*amt*R(-.25,.25))}
function V(a,x,m){var q=SV.QUARTER,d=x.d;if(x.particle||x.weak||d<q*1.15)return;var p=d>=q*3?.92:d>=q*2?.72:d>=q*1.5?.42:.16;p*=.55+W(x)*.55;if(Math.abs(x.next)>=5)p*=.78;if(x.sameNext)p*=1.12;if(Math.random()>C(p,0,.96))return;var s=x.n.getOnset()+d*PROFILE.onset,e=x.n.getEnd(),len=e-s,cy=Math.min(7,Math.max(1,Math.round(d/q*PROFILE.rate))),pts=cy*2+1,dep=PROFILE.vib*m*(.62+W(x)*.38),sg=Q([-1,1]);for(var i=0;i<=pts;i++){var z=i/pts,v=dep*(i%2===0?-1:1)*sg*R(1-PROFILE.irr,1+PROFILE.irr);v*=C((z+.12)/.25,0,1)*(1-Math.max(0,z-.72)*.8);P(a,s+len*z,v)}P(a,e-d*.06,-dep*R(.25,.55));P(a,e,0)}
function F(a,x,m){if(!x.last||x.d<SV.QUARTER*.75)return;var e=x.n.getEnd();P(a,e-x.d*.16,-PROFILE.fall*m*R(.45,.8));P(a,e-x.d*.05,-PROFILE.fall*m);P(a,e,0)}
function main(){var r=SV.showCustomDialog({title:SV.T(PROFILE.title),message:SV.T("Sparse early-VOCALOID pitch grammar"),buttons:"OkCancel",widgets:[{name:"int",type:"ComboBox",label:"Intensity",choices:["Light","Medium","Strong","Extreme"],default:1},{name:"vib",type:"ComboBox",label:"Vibrato",choices:["Off","Light","Classic","Heavy"],default:2},{name:"acc",type:"ComboBox",label:"Accents",choices:["Low","Medium","High","Very High"],default:2},{name:"clear",type:"ComboBox",label:"Clear existing pitchDelta",choices:["Yes","No"],default:0}]});if(!r.status)return;var ns=SV.getMainEditor().getSelection().getSelectedNotes();if(!ns.length){SV.showMessageBox(SV.T(PROFILE.title),SV.T("Please select notes."));return}ns.sort(function(a,b){return a.getOnset()-b.getOnset()});var im=[.65,1,1.45,2][+r.answers.int],vm=[0,.55,1,1.45][+r.answers.vib],am=[.5,1,1.7,2.5][+r.answers.acc];if(+r.answers.clear===0)for(var c=0;c<ns.length;c++)ns[c].getParent().getParameter("pitchDelta").remove(ns[c].getOnset(),ns[c].getEnd());for(var i=0;i<ns.length;i++){var x=I(ns,i),a=x.n.getParent().getParameter("pitchDelta");A(a,x,im);X(a,x,im*am);if(vm)V(a,x,vm);F(a,x,im)}SV.finish()}
