var SCRIPT_TITLE = "VOCALOID Tuning Lab";
function getClientInfo() { return { name: SV.T(SCRIPT_TITLE), category: "eli_lab - VOCALOID Tuning Lab", author: "eli_lab", versionNumber: 5, minEditorVersion: 67840 }; }
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
var PARTICLES=["は","が","を","に","へ","と","で","も","の","ね","よ","さ","ぞ","な","や"];
var WEAK=["っ","ッ","ー","ん","ン","る","れ","ろ","す","つ","く","き"];
var SPECIAL=["っ","ッ","ー","ん","ン"];
var SMALL="ゃゅょぁぇぃぉぅゎャュョァェィォゥヮ";
var RNG=Math.random;
function seedRandom(seed){var s=(parseInt(seed,10)||1)>>>0;if(!s)s=1;RNG=function(){s=(1664525*s+1013904223)>>>0;return s/4294967296;};}
function rand(a,b){return a+RNG()*(b-a);} function pick(a){return a[Math.floor(RNG()*a.length)];}
function mora(s){s=s||"";if(PARTICLES.indexOf(s)>=0)return"particle";if(SPECIAL.indexOf(s)>=0)return"special";if(WEAK.indexOf(s)>=0)return"weak";for(var i=0;i<s.length;i++)if(SMALL.indexOf(s.charAt(i))>=0)return"contracted";return s?"content":"unknown";}
function nb(n,o){var g=n.getParent(),i=n.getIndexInParent()+o;return i<0||i>=g.getNumNotes()?null:g.getNote(i);}
function analyze(n){var p=nb(n,-1),x=nb(n,1),q=SV.QUARTER,d=n.getDuration(),k=mora(n.getLyrics()),pi=p?n.getPitch()-p.getPitch():0,ni=x?x.getPitch()-n.getPitch():0,start=!p||n.getOnset()-p.getEnd()>q*.20,end=!x||x.getOnset()-n.getEnd()>q*.20;
var imp=.20+clamp(d/(q*2),0,1)*.30+clamp(Math.max(Math.abs(pi),Math.abs(ni))/7,0,1)*.30;if(start)imp+=.08;if(end)imp+=.12;if(p&&p.getPitch()===n.getPitch())imp-=.08;if(x&&x.getPitch()===n.getPitch())imp+=.06;if(k==="particle")imp-=.26;if(k==="weak"||k==="special")imp-=.10;imp=clamp(imp,.04,1.35);
var acc=imp;if(d<q*.70)acc+=.12;if(Math.abs(pi)>=5)acc+=.16;if(Math.abs(ni)>=5)acc+=.20;if(end)acc+=.14;if(k==="particle")acc-=.30;acc=clamp(acc,0,1.5);
var vib=0;if(k==="content"||k==="contracted"){if(d>=q*3)vib=.94;else if(d>=q*2)vib=.64;else if(d>=q*1.5)vib=.28;else if(d>=q*1.25)vib=.08;vib*=.62+imp*.50;if(Math.abs(ni)>=5)vib*=.68;if(Math.abs(pi)>=5)vib*=.82;if(x&&x.getPitch()===n.getPitch())vib*=1.2;if(end)vib*=1.15;vib=clamp(vib,0,.98);}
return{kind:k,imp:imp,acc:acc,vib:vib,pi:pi,ni:ni,start:start,end:end};}
function add(auto,n,pts){var s=n.getOnset(),e=n.getEnd(),last=null;for(var i=0;i<pts.length;i++){var t=Math.round(s+clamp(pts[i][0],0,1)*(e-s));if(last!==null&&t<=last)t=last+1;if(t>e)t=e;auto.add(t,clamp(pts[i][1],-1200,1200));last=t;}}
var MODELS=[{name:"Classic",attack:14,vib:5,cycles:2,onset:.48,ending:7},{name:"V1",attack:18,vib:6,cycles:2,onset:.45,ending:9},{name:"V2",attack:23,vib:8,cycles:3,onset:.40,ending:12},{name:"2008 Emotional",attack:28,vib:10,cycles:3,onset:.32,ending:15},{name:"2008 Extreme",attack:38,vib:14,cycles:4,onset:.25,ending:22}];
function attack(auto,n,a,p,profile,extreme){var d=n.getDuration(),dir=a.pi>0?1:a.pi<0?-1:a.ni>0?1:a.ni<0?-1:pick([-1,1]),amt=profile.attack*(.30+a.imp*.78)*(.55+clamp(Math.abs(a.pi)/7,0,1)*.65);if(extreme)amt*=1.22;if(a.kind==="particle")amt*=.28;if(a.kind==="weak"||a.kind==="special")amt*=.45;if(a.pi===0&&a.ni===0)amt*=.72;add(auto,n,[[0,0],[rand(.018,.055),dir*amt*rand(.45,.95)],[rand(.07,.15),dir*amt*rand(.35,extreme?1.1:.72)],[rand(.16,.26),rand(-2,2)]]);}
function accent(auto,n,a,level,extreme){if(a.acc<.06)return;var d=n.getDuration(),dir=a.ni>0?1:a.ni<0?-1:a.pi>0?1:-1,amt=level*a.acc;if(a.kind==="particle")amt*=.16;if(a.kind==="weak"||a.kind==="special")amt*=.45;if(extreme)amt*=1.22;add(auto,n,[[0,0],[rand(.20,.34),dir*amt*rand(.45,1)],[rand(.40,.58),dir*amt*rand(-.20,.18)],[.75,0]]);}
function vibrato(auto,n,a,depth,cycles,onset,extreme,instability){if(a.vib<=0)return;var s=n.getOnset(),e=n.getEnd(),d=e-s,vs=s+d*onset,vd=e-vs;if(vd<SV.QUARTER*.45)return;var points=Math.max(5,cycles*2+1),phase=rand(-.35,.35),prev=0;for(var i=0;i<=points;i++){var x=i/points,t=vs+vd*x,w=Math.sin(x*cycles*Math.PI*2+phase);if(extreme)w=w*.8+Math.sin(x*cycles*Math.PI*4+phase)*.2;var env=clamp(x/.18,0,1)*(1-Math.max(0,x-.78)*.8),v=w*depth*env*rand(1-instability,1+instability);v=prev*.15+v*.85;prev=v;auto.add(Math.round(t),clamp(v,-1200,1200));}auto.add(Math.round(e),0);}
function main(){var r=SV.showCustomDialog({title:SV.T(SCRIPT_TITLE),message:"Context-aware VOCALOID-era pitch generator. Analysis is calculated directly from the current note group; no cache or pre-analysis step is required.",buttons:"OkCancel",widgets:[{name:"era",type:"ComboBox",label:"Model",choices:["Classic","V1","V2","2008 Emotional","2008 Extreme"],default:4},{name:"accent",type:"ComboBox",label:"Accent intelligence",choices:["Low","Medium","High","Extreme"],default:2},{name:"vibrato",type:"ComboBox",label:"Vibrato coverage",choices:["Sparse","Classic","Aggressive","Off"],default:1},{name:"instability",type:"ComboBox",label:"Instability",choices:["Low","Medium","High","Extreme"],default:2},{name:"clear",type:"ComboBox",label:"Clear selected Pitch Deviation",choices:["Yes","No"],default:0},{name:"seed",type:"TextBox",label:"Seed",default:"2008"}]});if(!r.status)return;seedRandom(r.answers.seed);var notes=SV.getMainEditor().getSelection().getSelectedNotes();if(!notes.length){SV.showMessageBox(SV.T(SCRIPT_TITLE),SV.T("Please select notes."));return;}notes.sort(function(a,b){return a.getOnset()-b.getOnset();});var profile=MODELS[parseInt(r.answers.era)],extreme=parseInt(r.answers.era)===4,accentLevel=[.55,.90,1.35,1.90][parseInt(r.answers.accent)],vMode=parseInt(r.answers.vibrato),inst=[.05,.12,.22,.34][parseInt(r.answers.instability)],coverage=[.55,.85,1.15,0][vMode];if(parseInt(r.answers.clear)===0)for(var c=0;c<notes.length;c++)notes[c].getParent().getParameter("pitchDelta").remove(notes[c].getOnset(),notes[c].getEnd());for(var i=0;i<notes.length;i++){var n=notes[i],a=analyze(n),auto=n.getParent().getParameter("pitchDelta");attack(auto,n,a,null,profile,extreme);accent(auto,n,a,accentLevel*12,extreme);if(vMode!==3&&RNG()<a.vib*coverage){vibrato(auto,n,a,profile.vib*(.80+inst*.55),profile.cycles,profile.onset,extreme,inst);}if(i===notes.length-1&&n.getDuration()>SV.QUARTER*.75)add(auto,n,[[.82,-profile.ending*(.75+inst*.5)],[.95,-profile.ending*(.35+inst*.35)],[1,0]]);}SV.finish();}
