var SCRIPT_TITLE="VOCALOID 2008 Extreme";
function getClientInfo(){return{name:SV.T(SCRIPT_TITLE),category:"eli_lab - VOCALOID Tuning Lab",author:"eli_lab",versionNumber:3,minEditorVersion:67840};}
function clamp(v,a,b){return Math.max(a,Math.min(b,v));}
var PARTICLES=["は","が","を","に","へ","と","で","も","の","ね","よ","さ","ぞ","な","や"],WEAK=["っ","ッ","ー","ん","ン","る","れ","ろ","す","つ","く","き"],SPECIAL=["っ","ッ","ー","ん","ン"],SMALL="ゃゅょぁぇぃぉぅゎャュョァェィォゥヮ";
var RNG=Math.random;function seedRandom(seed){var s=(parseInt(seed,10)||1)>>>0;if(!s)s=1;RNG=function(){s=(1664525*s+1013904223)>>>0;return s/4294967296;};}function rand(a,b){return a+RNG()*(b-a);}
function mora(s){s=s||"";if(PARTICLES.indexOf(s)>=0)return"particle";if(SPECIAL.indexOf(s)>=0)return"special";if(WEAK.indexOf(s)>=0)return"weak";for(var i=0;i<s.length;i++)if(SMALL.indexOf(s.charAt(i))>=0)return"contracted";return s?"content":"unknown";}
function nb(n,o){var g=n.getParent(),i=n.getIndexInParent()+o;return i<0||i>=g.getNumNotes()?null:g.getNote(i);}
function analyze(n){var p=nb(n,-1),x=nb(n,1),q=SV.QUARTER,d=n.getDuration(),k=mora(n.getLyrics()),pi=p?n.getPitch()-p.getPitch():0,ni=x?x.getPitch()-n.getPitch():0,start=!p||n.getOnset()-p.getEnd()>q*.2,end=!x||x.getOnset()-n.getEnd()>q*.2;var a=.20+clamp(d/(q*2),0,1)*.30+clamp(Math.max(Math.abs(pi),Math.abs(ni))/7,0,1)*.30;if(start)a+=.08;if(end)a+=.12;if(p&&p.getPitch()===n.getPitch())a-=.08;if(x&&x.getPitch()===n.getPitch())a+=.06;if(k==="particle")a-=.26;if(k==="weak"||k==="special")a-=.10;var acc=a;if(d<q*.7)acc+=.12;if(Math.abs(pi)>=5)acc+=.16;if(Math.abs(ni)>=5)acc+=.20;if(end)acc+=.14;if(k==="particle")acc-=.30;var vib=0;if(k==="content"||k==="contracted"){if(d>=q*3)vib=.94;else if(d>=q*2)vib=.64;else if(d>=q*1.5)vib=.28;else if(d>=q*1.25)vib=.08;vib*=.62+clamp(a,.04,1.35)*.50;if(Math.abs(ni)>=5)vib*=.68;if(Math.abs(pi)>=5)vib*=.82;if(x&&x.getPitch()===n.getPitch())vib*=1.2;if(end)vib*=1.15;}return{kind:k,acc:clamp(acc,0,1.5),vib:clamp(vib,0,.98),pi:pi,ni:ni,start:start,end:end};}
function add(auto,n,pts){var s=n.getOnset(),e=n.getEnd(),last=null;for(var i=0;i<pts.length;i++){var t=Math.round(s+clamp(pts[i][0],0,1)*(e-s));if(last!==null&&t<=last)t=last+1;if(t>e)t=e;auto.add(t,clamp(pts[i][1],-1200,1200));last=t;}}
function main(){var r=SV.showCustomDialog({title:SV.T(SCRIPT_TITLE),message:"Extreme 2008 laboratory preset. Context is calculated directly from the note group; no cache or analyzer pass is required.",buttons:"OkCancel",widgets:[{name:"amount",type:"ComboBox",label:"Intensity",choices:["Strong","Extreme","Maximum"],default:1},{name:"vibrato",type:"ComboBox",label:"Vibrato",choices:["Sparse","Classic","Aggressive","Mechanical"],default:2},{name:"clear",type:"ComboBox",label:"Clear selected Pitch Deviation",choices:["Yes","No"],default:0},{name:"seed",type:"TextBox",label:"Seed",default:"2008"}]});if(!r.status)return;seedRandom(r.answers.seed);var notes=SV.getMainEditor().getSelection().getSelectedNotes();if(!notes.length){SV.showMessageBox(SV.T(SCRIPT_TITLE),SV.T("Please select notes."));return;}notes.sort(function(a,b){return a.getOnset()-b.getOnset();});var scale=[1.25,1.65,2.05][parseInt(r.answers.amount)],vm=parseInt(r.answers.vibrato),depth=[9,13,18,22][vm],mechanical=vm===3;if(parseInt(r.answers.clear)===0)for(var c=0;c<notes.length;c++)notes[c].getParent().getParameter("pitchDelta").remove(notes[c].getOnset(),notes[c].getEnd());for(var i=0;i<notes.length;i++){var n=notes[i],a=analyze(n),d=n.getDuration(),start=n.getOnset(),auto=n.getParent().getParameter("pitchDelta"),dir=a.ni>0?1:a.ni<0?-1:a.pi>0?1:a.pi<0?-1:(RNG()<.5?-1:1),jump=clamp(Math.max(Math.abs(a.pi),Math.abs(a.ni))/5,0,1.5),amt=26*scale*(.65+jump*.55)*(.70+a.acc*.55);if(a.kind==="particle")amt*=.22;if(a.kind==="weak"||a.kind==="special")amt*=.45;if(a.start)amt*=1.08;if(a.end)amt*=1.16;if(a.pi===0&&a.ni===0)amt*=1.12;add(auto,n,[[0,0],[rand(.018,.05),dir*amt*rand(.55,1)],[rand(.07,.14),dir*amt*rand(.30,.95)],[rand(.16,.25),rand(-4,4)]]);if(a.kind!=="particle"&&a.kind!=="weak"&&a.kind!=="special"&&d>=SV.QUARTER*1.25){var probability=clamp(a.vib*1.20,0,.99);if(Math.abs(a.ni)>=5)probability*=.65;if(RNG()<probability){var vs=start+d*(mechanical?.22:.27),ve=n.getEnd(),cycles=Math.min(8,Math.max(2,Math.round(d/SV.QUARTER*(mechanical?2:1.55)))),points=cycles*2+1;for(var p=0;p<=points;p++){var x=p/points,w=mechanical?(p%2?-1:1):Math.sin(x*cycles*Math.PI*2+rand(-.25,.25)),env=clamp(x/.15,0,1)*(1-Math.max(0,x-.82)*.9);auto.add(Math.round(vs+(ve-vs)*x),clamp(w*depth*scale*env*rand(.82,1.18),-1200,1200));}auto.add(Math.round(ve),0);}}if(i===notes.length-1&&d>SV.QUARTER)add(auto,n,[[.84,-22*scale],[.95,-28*scale],[1,0]]);}SV.finish();}
